# Generated by Django 2.2.1 on 2019-05-30 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paperboy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_house_number', models.IntegerField()),
                ('ending_house_number', models.IntegerField()),
                ('paperboy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='paperboy.Paperboy')),
            ],
        ),
    ]
